=== Quick Start

==== Default mapping

To declare a domain class to be searchable, the simplest way is to define the following static property in the code:

[source,groovy]
----
static searchable = true
----

The plugin will generate a default mapping for each properties of the domain.

==== Custom mapping

You can customize how each properties are mapped to the index using a closure. The syntax is similar to GORM's mapping DSL.

[source,groovy]
----
static searchable = {
    // mapping DSL...
}
----

See below for more details on the mapping DSL.

==== Limit properties with only/except
`only` and `except` are used to limit the properties that are made searchable.
You may not define both except & only settings at the same time.

The following code will only map the 'message' property, any others will be ignored.

[source, groovy]
----
class Tweet {
    static searchable = {
        only = 'message'
    }
    String message
    String someUselessField
}
----

The following code will map all properties except the one specified.

[source, groovy]
----
class Tweet {
    static searchable = {
        except = 'someUselessField'
    }
    String message
    String someUselessField
}
----

You can use a Collection to specify several properties.

[source, groovy]
----
class Tweet {
    static searchable = {
        except = ['someUselessField', 'userName']
    }
    String message
    String userName
    String someUselessField
}
----

[NOTE]
====
The properties that are ignored will not be sent to ElasticSearch. It also means that when you will get back a domain
from ElasticSearch, some fields that are not supposed to be null, may still be null.
====
