[[index]]
=== index

#### Purpose

Index domain instances to ElasticSearch.

Depending on whether a single instance is provided or multiple ones, it will executed an isolated index request or it will make use of ElasticSearch's https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk.html[Bulk API].
The first one will minimise the latency between index requests and the documents being available for search whilst the second one minimises the amount of I/O, reusing the client's connections for a single bulk request.

Decide which implementation to use based on your needs.

[NOTE]
====
Any domains not marked as `@Searchable` will be ignored.
====

#### Examples

[source, groovy]
----
// Index a specific domain instance
MyDomain md1 = new MyDomain(value:'that')
MyDomain md2 = new MyDomain(value:'that')
md1.save()
md2.save()
elasticSearchService.index(md)

// Index multiple instances
MyDomain md1 = new MyDomain(value:'that')
MyDomain md2 = new MyDomain(value:'that')
md1.save()
md2.save()
elasticSearchService.index(md1, md2)

// Index a collection of domain instances
def ds = [new MyDomain(value:'that'), new MyOtherDomain(name:'this'), new MyDomain(value:'thatagain')]
ds*.save()
elasticSearchService.index(ds)

----

##### Description

`index` signatures:

[source, groovy]
----
IndexResponse index(Object domainObject)
BulkIndexResponse index(Object ... domainObject)
BulkIndexResponse index(Collection<Domain> domainObjects)
----

##### Parameters

* `Object` domainObject - The domain object to index. The document indexed on ElasticSearch will be built using the `ElasticSearchMarsaller` implementation  provided on the domains `@Mapping` annotation
* `Collection<Domain>` domainObjects - A `Collection` of domain instances to index.
* `Object...` domain - Same as `Collection<Domain>`, but with an ellipsis.


##### Returned value
`IndexResponse` for one-off index requests.
`BulkIndexResponse` when indexing multiple domain instances.
`null` if no request was made (ie. the provided domain objects where not `@Searchable`)
