[[search]]
=== search

#### Purpose

Search for instances of a given domain class given a search query. Queries are built using Elasticsearch's Java API `QueryBuilder`
In contrast with the original `elasticsearch-grails-plugin`, instead of marshalled domain objects, the returned value is an ElasticSearch's Java API `SearchResponse` instance. It is up to the user whether to marshall the search results into domain objects.

#### Examples

[source, groovy]
----
import org.elasticsearch.action.search.SearchResponse
import static org.elasticsearch.index.query.QueryBuilders.*

SearchResponse response = elasticSearchService.search(FooDomain, queryStringQuery('search term'))
SearchResponse response = elasticSearchService.search(BarDomain, matchQuery('fieldName', 'fieldValue'))

SearchResponse response = elasticSearchService.search(MyDomain, boolQuery().
                .must(termQuery('title', 'Captain'))
                .should(termQuery('name', 'Kirk'))
                .should(termQuery('name', 'Picard'))
                .filter(termQuery('franchise', 'Star Trek'))
)
----

##### Description

`search` signatures:

[source, groovy]
----
SearchResponse search(Class domainClass, QueryBuilder query)
----

##### Parameters

* `Class` domainClass - The class to search against.
* `QueryBuilder` query - The query to execute.


##### Returned value

ElasticSearch's Java API `SearchResponse`


### ElasticSearch Builders

ElasticSearch provides many builders (e.g. QueryBuilders) and builder factories (ending with *Builders*, e.g. QueryBuilders).
The factories provide methods for creating the concrete builders - e.g. QueryBuilders.matchQuery() produces a MatchQueryBuilder, which can be used to create a match query.

Here is a list of builder factories:

* org.elasticsearch.index.mapper.MapperBuilders
* org.elasticsearch.index.query.QueryBuilders
* org.elasticsearch.index.query.FilterBuilders
* org.elasticsearch.search.sort.SortBuilders
* org.elasticsearch.search.facet.FacetBuilders
* org.elasticsearch.cluster.routing.RoutingBuilders

#### Migrating from `elastic-search-grails-plugin`

`elasticsearch-grails-plugin` provides a diversity of interfaces on the search method, allowing querying by `String`, `QueryBuilder`, `Closure`, etc.
Whilst this might be more flexlible for the user, all these implementations eventually convert the query into a `QueryBuilder` implementation on Elasticsearch. Since the `QueryBuilder` object allows flexibility to compose queries of any complexity and will always be compatible with Elasticsearch's Java API, this plugin only supports yet this interface.

##### Queries and filters

Since Elasticsearch `2.x` the concept of filters has changed and these are now part of a `boolQuery`. To filter in a query, refer to the examples above.

##### Search params: fetchSource, sort ...

What happened to all my params? To further customise your search, you can opt for two alternatives:

* Use `SearchRequestBuilder ElasticSearchService.prepareSearch(...)` which allows you to fully customise your search request
* Use ElasticSearch's client available via `Client ElasticSearchService.getClient()`

