[[unindex]]

=== unindex

#### Purpose

Remove domain instances from the ElasticSearch indices, triggering a single request against the ElasticSearch index.
Depending on whether a single instance is provided or multiple ones, the request sent will be an isolated `Delete` request or a `BulkRequest` incluying all delete operations.

#### Examples

[source, groovy]
----
// Unindex one instance
elasticSearchService.unindex(myDomainInstance)

// Unindex several domain instances
elasticSearchService.unindex(instance1, instance2, instance3)

// Unindex a collection of domain instances
Collection ds = [new MyDomain(value:'that'), new MyOtherDomain(name:'this'), new MyDomain(value:'thatagain')]
ds*.save()
elasticSearchService.unindex(ds)

[NOTE]
====
Any domains not marked as `@Searchable` will be ignored.
====


----

##### Description

`unindex` signatures:

[source, groovy]
----
BulkResponse unindex(Collection<Domain> domainInstances)
BulkResponse unindex(Object ... domainInstances)
DeleteResponse unindex(Object domainInstance)
----

##### Parameters

* `Collection<Domain>` domains - A `Collection` of domain instances to unindex.
* `Domain...` domain - Same as `Collection<Domain>`, but with an ellipsis.
* `Object` domainInstance - A single instance to unindex.

##### Returned value

If a single instance is provided a delete request is executed, therefore a `DeleteResponse` is returned.

When multiple instances are provided (either via a `Collection` or multiple arguments) a `BulkResponse` is returned.

`null` is returned if no request was sent ElasticSearch (ie. because the provided instance is not `@Searchable`)
