[[index]]
=== index

#### Purpose

Index specific domain instances to ElasticSearch.

This method is a shorcut to `elasticSearchService.index(Object domainObject)` implementation. Since a single instance is provided, the plugin will execute a single `IndexRequest`. This reduces the latency between index operation the document being returned upon search, but increases the amount of I/O (network) with the ElasticSearch nodes.
To make use ElasticSearch's https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk.html[Bulk API], you can use `elasticSearchService.index(Collection domainObjects)` instead.

Use and combine both based on your specific needs.

[NOTE]
====
Only domains that are `@Searchable` have this method injected.
====

#### Examples

[source, groovy]
----
// Index a specific domain instance
MyDomain md = new MyDomain(value:'that').save()
md.index()

----

##### Description

`index` signatures:

[source, groovy]
----
// Index a specific domain instance
IndexResponse index()
----

##### Parameters

None

##### Returned value

An instance of ElasticSearch Java API's `IndexResponse` indicating the result of the operation
