[[unindex]]
=== unindex

#### Purpose

Delete specific domain instances from the ElasticSearch indices.

This method is a shorcut to `elasticSearchService.unindex(Object domainObject)` implementation. Since a single instance is provided, the plugin will execute a single `IndexRequest`. This reduces the latency between index operation the document being returned upon search, but increases the amount of I/O (network) with the ElasticSearch nodes.
To make use ElasticSearch's https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk.html[Bulk API], you can use `elasticSearchService.unindex(Collection domainObjects)` instead.

Use and combine both based on your specific needs.

[NOTE]
====
Only domains that are `@Searchable` have this method injected.
====

#### Examples

[source, groovy]
----
// Unindex a specific domain instance
MyDomain md = MyDomain.get(1)
md.unindex()

----

##### Description

`unindex` signatures:

[source, groovy]
----
// Unindex a specific domain instance
DeleteResponse unindex()
----

##### Parameters

None

#### Returned value

An instance of ElasticSearch's Java API `DeleteResponse` detailing the response of the operation.

